//! # D-Bus interface proxy for: `org.freedesktop.ModemManager1.Modem.Messaging`
//!
//! This code was generated by `zbus-xmlgen` `4.1.0` from D-Bus introspection data.
//! Source: `Interface '/org/freedesktop/ModemManager1/Modem/4' from service 'org.freedesktop.ModemManager1' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
	interface = "org.freedesktop.ModemManager1.Modem.Messaging",
	default_service = "org.freedesktop.ModemManager1",
	default_path = "/org/freedesktop/ModemManager1/Modem/4"
)]
trait Messaging {
	/// Create method
	fn create(
		&self,
		properties: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
	) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

	/// Delete method
	fn delete(&self, path: &zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

	/// List method
	fn list(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

	/// Added signal
	#[zbus(signal)]
	fn added(&self, path: zbus::zvariant::ObjectPath<'_>, received: bool) -> zbus::Result<()>;

	/// Deleted signal
	#[zbus(signal)]
	fn deleted(&self, path: zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

	/// DefaultStorage property
	#[zbus(property)]
	fn default_storage(&self) -> zbus::Result<u32>;

	/// Messages property
	#[zbus(property)]
	fn messages(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

	/// SupportedStorages property
	#[zbus(property)]
	fn supported_storages(&self) -> zbus::Result<Vec<u32>>;
}
