//! # D-Bus interface proxy for: `org.freedesktop.ModemManager1.Modem.Signal`
//!
//! This code was generated by `zbus-xmlgen` `4.1.0` from D-Bus introspection data.
//! Source: `Interface '/org/freedesktop/ModemManager1/Modem/4' from service 'org.freedesktop.ModemManager1' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
	interface = "org.freedesktop.ModemManager1.Modem.Signal",
	default_service = "org.freedesktop.ModemManager1",
	default_path = "/org/freedesktop/ModemManager1/Modem/4"
)]
trait Signal {
	/// Setup method
	fn setup(&self, rate: u32) -> zbus::Result<()>;

	/// SetupThresholds method
	fn setup_thresholds(
		&self,
		settings: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
	) -> zbus::Result<()>;

	/// Cdma property
	#[zbus(property)]
	fn cdma(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

	/// ErrorRateThreshold property
	#[zbus(property)]
	fn error_rate_threshold(&self) -> zbus::Result<bool>;

	/// Evdo property
	#[zbus(property)]
	fn evdo(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

	/// Gsm property
	#[zbus(property)]
	fn gsm(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

	/// Lte property
	#[zbus(property)]
	fn lte(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

	/// Nr5g property
	#[zbus(property)]
	fn nr5g(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

	/// Rate property
	#[zbus(property)]
	fn rate(&self) -> zbus::Result<u32>;

	/// RssiThreshold property
	#[zbus(property)]
	fn rssi_threshold(&self) -> zbus::Result<u32>;

	/// Umts property
	#[zbus(property)]
	fn umts(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;
}
