//! # D-Bus interface proxy for: `org.freedesktop.ModemManager1.Modem.Modem3gpp.Ussd`
//!
//! This code was generated by `zbus-xmlgen` `4.1.0` from D-Bus introspection data.
//! Source: `Interface '/org/freedesktop/ModemManager1/Modem/4' from service 'org.freedesktop.ModemManager1' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
	interface = "org.freedesktop.ModemManager1.Modem.Modem3gpp.Ussd",
	default_service = "org.freedesktop.ModemManager1",
	default_path = "/org/freedesktop/ModemManager1/Modem/4"
)]
trait Ussd {
	/// Cancel method
	fn cancel(&self) -> zbus::Result<()>;

	/// Initiate method
	fn initiate(&self, command: &str) -> zbus::Result<String>;

	/// Respond method
	fn respond(&self, response: &str) -> zbus::Result<String>;

	/// NetworkNotification property
	#[zbus(property)]
	fn network_notification(&self) -> zbus::Result<String>;

	/// NetworkRequest property
	#[zbus(property)]
	fn network_request(&self) -> zbus::Result<String>;

	/// State property
	#[zbus(property)]
	fn state(&self) -> zbus::Result<u32>;
}
